### ISSUE TITLE
LinkidIntoLtpWriter - LILW

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/policingProfile#3]
### Category
HighPerformanceNetworkInterface

### Description
Planning data (includes content of legacy databases like x:akta or APT) is identified by IDs generated by Telefonica (e.g. network element ID or link ID). Actual configuration data, which has been retrieved from the network, is identified by IDs (e.g. LTP UUID) that have been generated by devices. Joining planning and configuration data is required for use cases like data reconciliation, configuration verification, live network view and many more. The LinkidIntoLtpWriter is calculating (might involve probability calculations) pairs of Telefonica Link ID and ONF LTP UUID and writes the Telefonica Link ID into the LTP inside the device.
### Dependency
- [x] #2 
### ApplicationOwner
Net yet defined
### Status
Candidate for being specified during the workshop series for ApplicationOwners

**Comment by ThorstenHeinze** [comment]
- [ ] What a stupid name - Please help and change it.
- [ ] ApplicationOwner should be removed 
- [ ] Proper Labels should be created
- [ ] Status should be removed
